In [32]:
import numpy as np

# Step 1: Define the sigmoid function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Step 2: Define the training function for the neural network
def train_neural_network(X, y, learning_rate, epochs):
    # Step 3: Initialize the weights and biases with random values
    input_neurons = X.shape[1]
    hidden_neurons = 4
    output_neurons = y.shape[1]
    hidden_weights = np.random.uniform(size=(input_neurons, hidden_neurons))
    hidden_bias = np.random.uniform(size=(1, hidden_neurons))
    output_weights = np.random.uniform(size=(hidden_neurons, output_neurons))
    output_bias = np.random.uniform(size=(1, output_neurons))

    # Step 4: Perform the training iterations
    for i in range(epochs):
        # Step 4.1: Forward propagation
        hidden_layer_activation = np.dot(X, hidden_weights) + hidden_bias
        hidden_layer_output = sigmoid(hidden_layer_activation)
        output_layer_activation = np.dot(hidden_layer_output, output_weights) + output_bias
        predicted_output = sigmoid(output_layer_activation)

        # Step 4.2: Backward propagation
        error = y - predicted_output
        d_predicted_output = error * sigmoid_derivative(predicted_output)
        error_hidden_layer = d_predicted_output.dot(output_weights.T)
        d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

        # Step 4.3: Update the weights and biases
        output_weights += np.dot(hidden_layer_output.T, d_predicted_output) * learning_rate
        output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
        hidden_weights += np.dot(X.T, d_hidden_layer) * learning_rate
        hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    # Step 5: Return the predicted output
    return predicted_output

# Function to convert a number to its binary representation
def number_to_binary(num):
    binary_str = bin(num)[2:]
    binary_list = [int(bit) for bit in binary_str]
    padded_binary = np.pad(binary_list, (5 - len(binary_list), 0), 'constant') if len(binary_list) < 5 else binary_list[:5]
    return padded_binary

# Function to convert a number to its one-hot encoded output
def number_to_output(num):
    if num == 0:
        return [1, 0, 0, 0]
    elif num == 1:
        return [0, 1, 0, 0]
    elif num == 2:
        return [0, 0, 1, 0]
    elif num == 39:
        return [0, 0, 0, 1]
    else:
        raise ValueError("Unsupported number")

# Function to generate training data for the specified numbers
def generate_training_data(numbers):
    X_train = []
    y_train = []
    for num in numbers:
        binary_representation = number_to_binary(num)
        X_train.append(binary_representation)
        y_train.append(number_to_output(num))
    return np.array(X_train), np.array(y_train)

# Train the neural network to recognize the numbers
training_numbers = [0, 1, 2, 39]
X_train, y_train = generate_training_data(training_numbers)
predicted_output = train_neural_network(X_train, y_train, learning_rate=0.1, epochs=10000)

print("Predicted outputs for training data:")
print(predicted_output)

# Test the neural network
def test_neural_network(X_test, hidden_weights, hidden_bias, output_weights, output_bias):
    predicted_output = sigmoid(np.dot(sigmoid(np.dot(X_test, hidden_weights) + hidden_bias), output_weights) + output_bias)
    return predicted_output

# Test data for numbers 0, 1, 2, 39
X_test = np.array([
    [1, 1, 1, 0, 1],  # Representing 0
    [0, 1, 1, 0, 0],  # Representing 1
    [1, 1, 0, 1, 1],  # Representing 2
    [1, 0, 0, 1, 1]   # Representing 39
])

# Provide the weights and biases for testing
hidden_weights = np.array([[0.1, 0.2, 0.3, 0.4], [0.5, 0.6, 0.7, 0.8], [0.9, 0.10, 0.11, 0.12], [0.13, 0.14, 0.15, 0.16], [0.17, 0.18, 0.19, 0.20]])
hidden_bias = np.array([[0.21, 0.22, 0.23, 0.24]])
output_weights = np.array([[0.25, 0.26, 0.27, 0.28], [0.29, 0.30, 0.31, 0.32], [0.33, 0.34, 0.35, 0.36], [0.37, 0.38, 0.39, 0.40]])
output_bias = np.array([[0.41, 0.42, 0.43, 0.44]])

print("\nPredicted outputs for test data:")
print(test_neural_network(X_test, hidden_weights, hidden_bias, output_weights, output_bias))


Predicted outputs for training data:
[[9.54118339e-01 2.86632753e-02 3.19994595e-02 1.99416534e-04]
 [3.51640808e-02 9.62618326e-01 4.44054789e-05 2.74770420e-02]
 [3.38501084e-02 7.57081284e-05 9.60617832e-01 3.28480748e-02]
 [9.97205723e-06 2.98309270e-02 2.71275845e-02 9.63252690e-01]]

Predicted outputs for test data:
[[0.80872466 0.81533131 0.82176006 0.82801221]
 [0.79433043 0.8008659  0.80724409 0.81346557]
 [0.80510913 0.81166166 0.81804368 0.82425627]
 [0.78097748 0.78734228 0.79357101 0.79966373]]


# Another One

In [33]:
import numpy as np

# Step 1: Define the sigmoid function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Step 2: Define the training function for the neural network
def train_neural_network(X, y, learning_rate, epochs):
    # Step 3: Initialize the weights and biases with random values
    input_neurons = X.shape[1]
    hidden_neurons = 4
    output_neurons = y.shape[1]
    hidden_weights = np.random.uniform(size=(input_neurons, hidden_neurons))
    hidden_bias = np.random.uniform(size=(1, hidden_neurons))
    output_weights = np.random.uniform(size=(hidden_neurons, output_neurons))
    output_bias = np.random.uniform(size=(1, output_neurons))

    # Step 4: Perform the training iterations
    for i in range(epochs):
        # Step 4.1: Forward propagation
        hidden_layer_activation = np.dot(X, hidden_weights) + hidden_bias
        hidden_layer_output = sigmoid(hidden_layer_activation)
        output_layer_activation = np.dot(hidden_layer_output, output_weights) + output_bias
        predicted_output = sigmoid(output_layer_activation)

        # Step 4.2: Backward propagation
        error = y - predicted_output
        d_predicted_output = error * sigmoid_derivative(predicted_output)
        error_hidden_layer = d_predicted_output.dot(output_weights.T)
        d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

        # Step 4.3: Update the weights and biases
        output_weights += np.dot(hidden_layer_output.T, d_predicted_output) * learning_rate
        output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
        hidden_weights += np.dot(X.T, d_hidden_layer) * learning_rate
        hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    # Step 5: Return the predicted output
    return predicted_output

# Example usage
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1],[0, 1, 0]])
y = np.array([[1], [1], [0], [0], [1]])

# Train the Neural Network
predicted_output = train_neural_network(X, y, learning_rate=0.1, epochs=10000)
print(predicted_output)


[[0.98146692]
 [0.98849108]
 [0.01369423]
 [0.01970438]
 [0.98604797]]
